### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by basepack** [ryangjchandler/blade-tabler-icons#12]
Hi,

It looks like we are missing some icons? For example `exclamation-mark` is not found.

**Comment by ryangjchandler** [comment]
@basepack The package needs an update. I'll do this later on today. Thanks for letting me know!

**Comment by ryangjchandler** [comment]
@basepack Sorry for the delay. v1.2.0 has been released with new icons.

**Comment by basepack** [comment]
Hi Ryan, great and many thanks for instead being so fast! 😄
