### ISSUE TITLE
Slows Down Test Suite refreshApplication()

### ISSUE THREAD

**Issue by hlipnick** [ryangjchandler/blade-tabler-icons#26]
I'm hesitant to even post this issue as I don't fully understand it, but want to at least bring it to your attention @ryangjchandler.  When installing this composer package, my app-wide test suite slows down by a factor of 2.7x (or up to 8x when running in parallel).  The slow down appears to happen in the `refreshApplication()` method of Laravel's test setup, but I'll admit my ignorance in not being able to pinpoint what in this package is causing that slowdown.

Resolution is fairly simple on my end (just swapping out icons for now) but wanted to open the issue both to point out the problem but also because I'd love to further my own understanding of where to unearth the details that could be causing the slowdown.

Thanks for the hardwork on this and other packages!

**Comment by nxgcx** [comment]
Same problem, there are major performance issues with this package, everyone should avoid using it.

**Comment by vid-ramadhan** [comment]
@nxgcx has this problem been resolved?
