### ISSUE TITLE
Fails to install when blade-ui-kit/icons installed at 0.5.1

### ISSUE THREAD

**Issue by snapey** [ryangjchandler/blade-tabler-icons#3]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ryangjchandler/blade-tabler-icons[v0.02, ..., v0.2.0] require blade-ui-kit/blade-icons ^0.4.3 -> found blade-ui-kit/blade-icons[0.4.3, 0.4.4, 0.4.5] but it conflicts with your root composer.json require (^0.5.1).
    - Root composer.json requires ryangjchandler/blade-tabler-icons ^0.2.0 -> satisfiable by ryangjchandler/blade-tabler-icons[v0.2.0, v0.02].

**Comment by ryangjchandler** [comment]
Need to update requirement in package. Will fix tomorrow and tag new release.

Thank you for spotting!

**Comment by snapey** [comment]
Thanks, all working now.
![Screenshot 2020-11-07 at 17 00 14](https://user-images.githubusercontent.com/328747/98447192-c4d39900-211a-11eb-920d-dec1bc01eb5b.png)
