### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by rbeier** [ryangjchandler/blade-tabler-icons#8]
Hi,

it looks like some icon are missing: 

```
InvalidArgumentException
Unable to locate a class or view for component [tabler-edit-circle]
```

----

tablericons now lists 1262 icons but the content of the svg directory only shows 1002 icons:

```
$ ls vendor/ryangjchandler/blade-tabler-icons/resources/svg/ | wc -l
    1002
```
 
Could you please update the package?

**Comment by ryangjchandler** [comment]
@rbeier I'll update it this weekend and also get some automation setup so that the master branch is always up to date.

**Comment by karimoninja** [comment]
@rbeier Once this request is merged the problem will be solved.
@ryangjchandler The icons version has been updated to the latest version.

**Comment by ryangjchandler** [comment]
@karimoninja Thanks! Please update to v0.5.0.
